config/routes.rb
Rails.application.routes.draw do
	root :to => 'home#index'
  get 'categories/index'

  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  get 'home/index'
	resources :posts
	resources :categories
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base 
	#attr_accessible :name
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	#attr_accessible :title, :body, :category_id, :author_id
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
	@categories = Category.all
  end

  def edit
  end

  def new
	@category = Category.new
  end
  
  def create
	@category = Category.create(cat_create);
	redirect_to categories_path
  end
  
  def cat_create
		params.require(:category).permit(:name)
  end

  def show
	@category = Category.find(params[:id])
	@title = @category.name
	@posts = @category.posts
  end
  
  def destroy
	@category = Category.find(params[:id])
	@category.destroy
	redirect_to categories_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end
	
	def show
		@post = Post.find(params[:id])
	end
	
	def new 
		@post = Post.new
		@category = Category.all
	end
	
	def create
		@post = Post.create(post_params_create)
		redirect_to posts_path, :notice => "Your post has been saved"
		# if @post.save
			# redirect_to posts_path, :notice => "Your post has been saved"
		# else
			# render "New"
		# end
	end
	
	def post_params_create
		params.require(:post).permit(:title, :body, :category_id)
	end
	
	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		# if @post.update_attributes(params[:post])
			# redirect_to post_path, :notice => "Your post has been updated"
		# else
			# render "edit"
		# end
		@post.update(post_params)
		redirect_to post_path
	end
	def post_params
	# we construct a strong parameters whitelist below
	# require(:post) means that the `params` hash MUST contain a :post key
	# permit(:title, :body, ...) = here we enumerate the attributes which we will accept from the form parameters; it acts as a whitelist
	params.require(:post).permit(:title, :body, :category_id) 
	end	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h2>List Categories</h2>

<ul>
<% @categories.each do |cat| %>
	<li> <%= link_to cat.name, cat %> </li>
<% end %>
</ul>

<%= link_to "Posts", posts_path %> || <%= link_to "Add New Category", new_category_path %> 

app/views/categories/new.html.erb
<h1> New Category  </h1>
<%= form_for @category do |f| %>
	<p> 
		<%= f.label :name %> <br>
		<%= f.text_field :name %> <br>
	</p>

	<p> 
		<%= f.submit "New Category" %>
	</p>
<% end %>
<%= link_to "Go Back", categories_path %>

app/views/categories/show.html.erb
<h2><%= @category.name %> Category</h2>

<% @posts.each do |post| %>
	<h3> <%= link_to post.title, @post %> </h3>
	<p> <%= post.body %> </p>
<% end %>
<%= link_to "Back", categories_path %> | <%= link_to "Delete", @category, :method => :delete %>

app/views/home/index.html.erb
<h1>Home of posts</h1>

<%= link_to "Recent Posts", posts_path %> || 
<%= link_to "Post by Category", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrubyblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1> Edit posts   </h1>
<%= form_for @post do |f| %>
	<p> 
		<%= f.label :title %> <br>
		<%= f.text_field :title %> <br>
	</p>
	<p>
		<%= f.label :body %> <br>
		<%= f.text_area :body %> <br>
	</p>
	<p>
		<%= f.select :category_id, Category.all.collect { |x| [x.name, x.id] }, {:include_blank => "Select One"} %> <br>
	</p>

	<p> 
		<%= f.submit "Update Post" %>
	</p>
<% end %>
<%= link_to "Go Back", post_path %>
	

app/views/posts/index.html.erb
<h1> Blog Posts </h1>

<ul>
<% @posts.each do |post| %>
	<li><div>
	<h3> <%= link_to post.title, post %> </h3>
	<p> <%= post.body %> <p>
	</div></li>
<% end %>

<ul>

<%= link_to "New Post", new_post_path %> || <%= link_to "Categories", categories_path %>

app/views/posts/new.html.erb
<h1> New post  </h1>
<%= form_for @post do |f| %>
	<p> 
		<%= f.label :title %> <br>
		<%= f.text_field :title %> <br>
	</p>
	<p>
		<%= f.label :body %> <br>
		<%= f.text_area :body %> <br>
	</p>
	<p>
		<%= f.select :category_id, Category.all.collect { |x| [x.name, x.id] }, {:include_blank => "Select One"} %> <br>
	</p>

	<p> 
		<%= f.submit "New Post" %>
	</p>
<% end %>

<%= link_to "Go Back", posts_path %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2> 
Category : <%= link_to @post.category.name, category_path(:id => @post.category.id) %> || 
<small>  <%= @post.created_at.strftime("%b %d, %Y") %>
<p><%= @post.body %></p>
<%= link_to "Edit Post", edit_post_path%> | <%= link_to "Delete", @post, :confirm => "Are you sure you want to delete?", :method => :delete %>
| <%= link_to "Back to Posts", posts_path %>